# Generated by Django 5.2.1 on 2025-06-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_rename_class_contents_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='CalenderEvent', max_length=200),
        ),
    ]
